name = "photo-a-day"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "photo-a-day-db"
database_id = "cd034ff2-9bdf-43f9-a4d5-05e28c84d965"

# R2 Bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "photo-a-day-images"

# Environment variables
[vars]
R2_PUBLIC_URL = "https://pub-1f5d91e3b4ca4a649f140c22f40dd7e5.r2.dev"
